package at.generic.search.resultmodel;

import java.util.HashMap;
import java.util.List;
import java.util.Vector;


/**
 * @author szabolcs
 * @version $Id: CorrResultModel.java,v 1.6 2006/03/18 15:24:09 szabolcs Exp $
 * $Author: szabolcs $  
 * $Revision: 1.6 $
 * 
 * Model for search results generated by Lucene
 * 
 */
public class CorrResultModel {
	private List foundCorrSet;					// List with foundCorrSet or EventAgg depending on search rank
	private String queryTime;					// query time 
	private int numberOfResults;				// number of results on the current page
	private String searchString;				// the original query string 
	private int numberOfFoundCorrEvents;		// the number of found elements (correlations or events depending on search rank)
	
	// browser logic
	private String showEventId;					// which event should be displayed
	private String showEventViewType;			// display eventdetails either raw or formatted way
	private HashMap showCorrEventId = new HashMap();	// which correlationsets are opened?
	private String termList = new String();		// the list of terms you searched for
	private HashMap foundEventtypes;			// identified eventtypes in resultset
	private boolean showRefineQuery = false;	// hide-show of refine query element
	private boolean showRefineQueryOption = true;	// hide-show the more... option, used in Context Search
	
	// pagination logic
	private int currentPage;
	private int nextPage;
	private int prevPage;
	private int maxPageSize;
	private int maxSearchResults; 				// aka page size
	private String exactSearch;
	
	// date range stuff
	private boolean dateRangeActive = false;
	private int lowerBoundDay;
	private int lowerBoundMonth;
	private int lowerBoundYear;
	private int upperBoundDay;
	private int upperBoundMonth; 
	private int upperBoundYear;
	
	// profile stuff
	private boolean profileChanged = false;		// has profile been applied or did it change?
	private String profileName;					// which is the current profilename?
	private List profileCons = new Vector();	// List with all profiles and filters
	
	/*
	public String getDateRangeLowerBound() {
		return lowerBoundYear + lowerBoundMonth + lowerBoundDay;
	}
	
	public String getDateRangeUpperBound() {
		return upperBoundYear + upperBoundMonth + upperBoundDay;
	} */
	/**
	 * @return Returns the foundCorrSet.
	 */
	public List getFoundCorrSet() {
		return foundCorrSet;
	}
	/**
	 * @param foundCorrSet The foundCorrSet to set.
	 */
	public void setFoundCorrSet(List foundCorrSet) {
		this.foundCorrSet = foundCorrSet;
	}
	/**
	 * @return Returns the numberOfResults.
	 */
	public int getNumberOfResults() {
		return numberOfResults;
	}
	/**
	 * @param numberOfResults The numberOfResults to set.
	 */
	public void setNumberOfResults(int numberOfResults) {
		this.numberOfResults = numberOfResults;
	}
	/**
	 * @return Returns the queryTime.
	 */
	public String getQueryTime() {
		return queryTime;
	}
	/**
	 * @param queryTime The queryTime to set.
	 */
	public void setQueryTime(String queryTime) {
		this.queryTime = queryTime;
	}
	/**
	 * @return Returns the searchString.
	 */
	public String getSearchString() {
		return searchString;
	}
	/**
	 * @param searchString The searchString to set.
	 */
	public void setSearchString(String searchString) {
		this.searchString = searchString;
	}
	/**
	 * @return Returns the showEventId.
	 */
	public String getShowEventId() {
		return showEventId;
	}
	/**
	 * @param showEventId The showEventId to set.
	 */
	public void setShowEventId(String showEventId) {
		this.showEventId = showEventId;
	}
	/**
	 * @return Returns the showEventViewType.
	 */
	public String getShowEventViewType() {
		return showEventViewType;
	}
	/**
	 * @param showEventViewType The showEventViewType to set.
	 */
	public void setShowEventViewType(String showEventViewType) {
		this.showEventViewType = showEventViewType;
	}
	/**
	 * @return Returns the showCorrEventId.
	 */
	public HashMap getShowCorrEventId() {
		return showCorrEventId;
	}
	/**
	 * @param showCorrEventId The showCorrEventId to set.
	 */
	public void setShowCorrEventId(HashMap showCorrEventId) {
		this.showCorrEventId = showCorrEventId;
	}
	
	/**
	 * @return Returns the termList.
	 */
	public String getTermList() {
		return termList;
	}
	/**
	 * @param termList The termList to set.
	 */
	public void setTermList(String termList) {
		this.termList = termList;
	}
	/**
	 * @return Returns the currentPage.
	 */
	public int getCurrentPage() {
		return currentPage;
	}
	/**
	 * @param currentPage The currentPage to set.
	 */
	public void setCurrentPage(int currentPage) {
		this.currentPage = currentPage;
		this.nextPage = currentPage + 1;
		if (this.currentPage > 1) 
			this.prevPage = currentPage - 1;
	}
	/**
	 * @return Returns the maxPageSize.
	 */
	public int getMaxPageSize() {
		return maxPageSize;
	}
	/**
	 * @param maxPageSize The maxPageSize to set.
	 */
	public void setMaxPageSize(int maxPageSize) {
		this.maxPageSize = maxPageSize;
	}
	/**
	 * @return Returns the nextPage.
	 */
	public int getNextPage() {
		return nextPage;
	}
	/**
	 * @param nextPage The nextPage to set.
	 */
	public void setNextPage(int nextPage) {
		this.nextPage = nextPage;
	}
	/**
	 * @return Returns the prevPage.
	 */
	public int getPrevPage() {
		return prevPage;
	}
	/**
	 * @param prevPage The prevPage to set.
	 */
	public void setPrevPage(int prevPage) {
		this.prevPage = prevPage;
	}
	/**
	 * @return Returns the numberOfFoundCorrEvents.
	 */
	public int getNumberOfFoundCorrEvents() {
		return numberOfFoundCorrEvents;
	}
	/**
	 * @param numberOfFoundCorrEvents The numberOfFoundCorrEvents to set.
	 */
	public void setNumberOfFoundCorrEvents(int numberOfFoundCorrEvents) {
		this.numberOfFoundCorrEvents = numberOfFoundCorrEvents;
	}
	/**
	 * @return Returns the maxSearchResults.
	 */
	public int getMaxSearchResults() {
		return maxSearchResults;
	}
	/**
	 * @param maxSearchResults The maxSearchResults to set.
	 */
	public void setMaxSearchResults(int maxSearchResults) {
		this.maxSearchResults = maxSearchResults;
	}
	/**
	 * @return Returns the exactSearch.
	 */
	public String getExactSearch() {
		return exactSearch;
	}
	/**
	 * @param exactSearch The exactSearch to set.
	 */
	public void setExactSearch(String exactSearch) {
		this.exactSearch = exactSearch;
	}
	/**
	 * @return Returns the foundEventtypes.
	 */
	public HashMap getFoundEventtypes() {
		return foundEventtypes;
	}
	/**
	 * @param foundEventtypes The foundEventtypes to set.
	 */
	public void setFoundEventtypes(HashMap foundEventtypes) {
		this.foundEventtypes = foundEventtypes;
	}
	/**
	 * @return Returns the showRefineQuery.
	 */
	public boolean isShowRefineQuery() {
		return showRefineQuery;
	}
	/**
	 * @param showRefineQuery The showRefineQuery to set.
	 */
	public void setShowRefineQuery(boolean showRefineQuery) {
		this.showRefineQuery = showRefineQuery;
	}
	/**
	 * @return Returns the showRefineQueryOption.
	 */
	public boolean isShowRefineQueryOption() {
		return showRefineQueryOption;
	}
	/**
	 * @param showRefineQueryOption The showRefineQueryOption to set.
	 */
	public void setShowRefineQueryOption(boolean showRefineQueryOption) {
		this.showRefineQueryOption = showRefineQueryOption;
	}
	/**
	 * @return Returns the dateRangeActive.
	 */
	public boolean isDateRangeActive() {
		return dateRangeActive;
	}
	/**
	 * @param dateRangeActive The dateRangeActive to set.
	 */
	public void setDateRangeActive(boolean dateRangeActive) {
		this.dateRangeActive = dateRangeActive;
	}
	/**
	 * @return Returns the lowerBoundDay.
	 */
	public int getLowerBoundDay() {
		return lowerBoundDay;
	}
	/**
	 * @param lowerBoundDay The lowerBoundDay to set.
	 */
	public void setLowerBoundDay(int lowerBoundDay) {
		this.lowerBoundDay = lowerBoundDay;
	}
	/**
	 * @return Returns the lowerBoundMonth.
	 */
	public int getLowerBoundMonth() {
		return lowerBoundMonth;
	}
	/**
	 * @param lowerBoundMonth The lowerBoundMonth to set.
	 */
	public void setLowerBoundMonth(int lowerBoundMonth) {
		this.lowerBoundMonth = lowerBoundMonth;
	}
	/**
	 * @return Returns the lowerBoundYear.
	 */
	public int getLowerBoundYear() {
		return lowerBoundYear;
	}
	/**
	 * @param lowerBoundYear The lowerBoundYear to set.
	 */
	public void setLowerBoundYear(int lowerBoundYear) {
		this.lowerBoundYear = lowerBoundYear;
	}
	/**
	 * @return Returns the upperBoundDay.
	 */
	public int getUpperBoundDay() {
		return upperBoundDay;
	}
	/**
	 * @param upperBoundDay The upperBoundDay to set.
	 */
	public void setUpperBoundDay(int upperBoundDay) {
		this.upperBoundDay = upperBoundDay;
	}
	/**
	 * @return Returns the upperBoundMonth.
	 */
	public int getUpperBoundMonth() {
		return upperBoundMonth;
	}
	/**
	 * @param upperBoundMonth The upperBoundMonth to set.
	 */
	public void setUpperBoundMonth(int upperBoundMonth) {
		this.upperBoundMonth = upperBoundMonth;
	}
	/**
	 * @return Returns the upperBoundYear.
	 */
	public int getUpperBoundYear() {
		return upperBoundYear;
	}
	/**
	 * @param upperBoundYear The upperBoundYear to set.
	 */
	public void setUpperBoundYear(int upperBoundYear) {
		this.upperBoundYear = upperBoundYear;
	}
	
	/**
	 * @return Returns the profileChanged.
	 */
	public boolean isProfileChanged() {
		return profileChanged;
	}
	/**
	 * @param profileChanged The profileChanged to set.
	 */
	public void setProfileChanged(boolean profileChanged) {
		this.profileChanged = profileChanged;
	}
	
	/**
	 * @return Returns the profileName.
	 */
	public String getProfileName() {
		return profileName;
	}
	/**
	 * @param profileName The profileName to set.
	 */
	public void setProfileName(String profileName) {
		this.profileName = profileName;
	}
	/**
	 * @return Returns the profileCons.
	 */
	public List getProfileCons() {
		return profileCons;
	}
	/**
	 * @param profileCons The profileCons to set.
	 */
	public void setProfileCons(List profileCons) {
		this.profileCons = profileCons;
	}



	
	
	
}	