package at.generic.search.resultmodel;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;


/**
 * @author szabolcs
 * @version $Id: CorrResultModel.java,v 1.2 2006/03/03 15:25:12 szabolcs Exp $
 * $Author: szabolcs $  
 * $Revision: 1.2 $
 * 
 * Model for search results generated by Lucene
 * 
 */
public class CorrResultModel {
	private List foundCorrSet;
	private String queryTime;
	private int numberOfResults;
	private String searchString;
	private String showEventId;
	private String showEventViewType;
	private HashMap showCorrEventId = new HashMap();
	private String termList = new String();
	
	
	/**
	 * @return Returns the foundCorrSet.
	 */
	public List getFoundCorrSet() {
		return foundCorrSet;
	}
	/**
	 * @param foundCorrSet The foundCorrSet to set.
	 */
	public void setFoundCorrSet(List foundCorrSet) {
		this.foundCorrSet = foundCorrSet;
	}
	/**
	 * @return Returns the numberOfResults.
	 */
	public int getNumberOfResults() {
		return numberOfResults;
	}
	/**
	 * @param numberOfResults The numberOfResults to set.
	 */
	public void setNumberOfResults(int numberOfResults) {
		this.numberOfResults = numberOfResults;
	}
	/**
	 * @return Returns the queryTime.
	 */
	public String getQueryTime() {
		return queryTime;
	}
	/**
	 * @param queryTime The queryTime to set.
	 */
	public void setQueryTime(String queryTime) {
		this.queryTime = queryTime;
	}
	/**
	 * @return Returns the searchString.
	 */
	public String getSearchString() {
		return searchString;
	}
	/**
	 * @param searchString The searchString to set.
	 */
	public void setSearchString(String searchString) {
		this.searchString = searchString;
	}
	/**
	 * @return Returns the showEventId.
	 */
	public String getShowEventId() {
		return showEventId;
	}
	/**
	 * @param showEventId The showEventId to set.
	 */
	public void setShowEventId(String showEventId) {
		this.showEventId = showEventId;
	}
	/**
	 * @return Returns the showEventViewType.
	 */
	public String getShowEventViewType() {
		return showEventViewType;
	}
	/**
	 * @param showEventViewType The showEventViewType to set.
	 */
	public void setShowEventViewType(String showEventViewType) {
		this.showEventViewType = showEventViewType;
	}
	/**
	 * @return Returns the showCorrEventId.
	 */
	public HashMap getShowCorrEventId() {
		return showCorrEventId;
	}
	/**
	 * @param showCorrEventId The showCorrEventId to set.
	 */
	public void setShowCorrEventId(HashMap showCorrEventId) {
		this.showCorrEventId = showCorrEventId;
	}
	
	/**
	 * @return Returns the termList.
	 */
	public String getTermList() {
		return termList;
	}
	/**
	 * @param termList The termList to set.
	 */
	public void setTermList(String termList) {
		this.termList = termList;
	}

	
	
	
	
}	