package at.generic.search.resultmodel;

import java.util.List;


/**
 * @author szabolcs
 * @version $Id: CorrResultModel.java,v 1.1 2006/02/27 14:58:25 szabolcs Exp $
 * $Author: szabolcs $  
 * $Revision:
 * 
 * Model for search results generated by Lucene
 * 
 */
public class CorrResultModel {
	private List foundCorrSet;
	private String queryTime;
	private int numberOfResults;
	private String searchString;
	
	
	/**
	 * @return Returns the foundCorrSet.
	 */
	public List getFoundCorrSet() {
		return foundCorrSet;
	}
	/**
	 * @param foundCorrSet The foundCorrSet to set.
	 */
	public void setFoundCorrSet(List foundCorrSet) {
		this.foundCorrSet = foundCorrSet;
	}
	/**
	 * @return Returns the numberOfResults.
	 */
	public int getNumberOfResults() {
		return numberOfResults;
	}
	/**
	 * @param numberOfResults The numberOfResults to set.
	 */
	public void setNumberOfResults(int numberOfResults) {
		this.numberOfResults = numberOfResults;
	}
	/**
	 * @return Returns the queryTime.
	 */
	public String getQueryTime() {
		return queryTime;
	}
	/**
	 * @param queryTime The queryTime to set.
	 */
	public void setQueryTime(String queryTime) {
		this.queryTime = queryTime;
	}
	/**
	 * @return Returns the searchString.
	 */
	public String getSearchString() {
		return searchString;
	}
	/**
	 * @param searchString The searchString to set.
	 */
	public void setSearchString(String searchString) {
		this.searchString = searchString;
	}
	
	
}	